
TEMPLATES = {
    'wedding': {
        'title': 'Organizacja Wesela',
        'description': 'Kompleksowy plan organizacji wesela z kluczowymi decyzjami',
        'icon': 'heart',
        'nodes': [
            {
                'title': 'Wybór Sali Weselnej',
                'description': 'Miejsce przyjęcia weselnego',
                'node_type': 'milestone',
                'section': 'accommodation',
                'order': 0,
                'estimated_cost_percent': 0,
                'children': [
                    {
                        'title': 'Sala w Hotelu (200 osób)',
                        'description': 'Elegancka sala hotelowa z pełnym zapleczem',
                        'node_type': 'decision',
                        'section': 'accommodation',
                        'order': 0,
                        'estimated_cost_percent': 35,
                        'score_comfort': 85,
                        'score_risk': 20,
                        'score_time': 70,
                        'score_pleasure': 80,
                    },
                    {
                        'title': 'Sala w Restauracji (150 osób)',
                        'description': 'Kameralna restauracja z ogródkiem',
                        'node_type': 'decision',
                        'section': 'accommodation',
                        'order': 0,
                        'estimated_cost_percent': 25,
                        'score_comfort': 75,
                        'score_risk': 30,
                        'score_time': 60,
                        'score_pleasure': 75,
                    },
                    {
                        'title': 'Plenerowa Sala (100 osób)',
                        'description': 'Wesele w plenerze, namiot eventowy',
                        'node_type': 'decision',
                        'section': 'accommodation',
                        'order': 0,
                        'estimated_cost_percent': 20,
                        'score_comfort': 60,
                        'score_risk': 60,
                        'score_time': 50,
                        'score_pleasure': 85,
                    },
                ]
            },
            {
                'title': 'Oprawa Muzyczna',
                'description': 'Muzyka i rozrywka na weselu',
                'node_type': 'milestone',
                'section': 'entertainment',
                'order': 1,
                'estimated_cost_percent': 0,
                'children': [
                    {
                        'title': 'Zespół Weselny (5 osób)',
                        'description': 'Profesjonalny zespół z wokalistką',
                        'node_type': 'decision',
                        'section': 'entertainment',
                        'order': 1,
                        'estimated_cost_percent': 15,
                        'score_comfort': 80,
                        'score_risk': 25,
                        'score_time': 75,
                        'score_pleasure': 85,
                    },
                    {
                        'title': 'DJ + Wodzirej',
                        'description': 'DJ z profesjonalnym sprzętem i wodzirej',
                        'node_type': 'decision',
                        'section': 'entertainment',
                        'order': 1,
                        'estimated_cost_percent': 10,
                        'score_comfort': 75,
                        'score_risk': 20,
                        'score_time': 80,
                        'score_pleasure': 80,
                    },
                ]
            },
            {
                'title': 'Catering i Menu',
                'description': 'Jedzenie i napoje dla gości',
                'node_type': 'milestone',
                'section': 'food',
                'order': 2,
                'estimated_cost_percent': 0,
                'children': [
                    {
                        'title': 'Menu Premium (5 dań)',
                        'description': 'Wykwintne menu z degustacją win',
                        'node_type': 'decision',
                        'section': 'food',
                        'order': 2,
                        'estimated_cost_percent': 30,
                        'score_comfort': 90,
                        'score_risk': 15,
                        'score_time': 65,
                        'score_pleasure': 90,
                    },
                    {
                        'title': 'Menu Standard (3 dania)',
                        'description': 'Klasyczne menu weselne',
                        'node_type': 'decision',
                        'section': 'food',
                        'order': 2,
                        'estimated_cost_percent': 20,
                        'score_comfort': 75,
                        'score_risk': 20,
                        'score_time': 70,
                        'score_pleasure': 75,
                    },
                ]
            },
        ]
    },
    'vacation': {
        'title': 'Wyjazd na Wakacje',
        'description': 'Planowanie wymarzonego wyjazdu wakacyjnego',
        'icon': 'plane',
        'nodes': [
            {
                'title': 'Transport',
                'description': 'Sposób dotarcia na miejsce',
                'node_type': 'milestone',
                'section': 'transport',
                'order': 0,
                'estimated_cost_percent': 0,
                'children': [
                    {
                        'title': 'Samolot (bezpośredni)',
                        'description': 'Lot bezpośredni, szybko i wygodnie',
                        'node_type': 'decision',
                        'section': 'transport',
                        'order': 0,
                        'estimated_cost_percent': 30,
                        'score_comfort': 85,
                        'score_risk': 25,
                        'score_time': 90,
                        'score_pleasure': 80,
                    },
                    {
                        'title': 'Samochód (własny)',
                        'description': 'Podróż własnym autem, elastyczność',
                        'node_type': 'decision',
                        'section': 'transport',
                        'order': 0,
                        'estimated_cost_percent': 15,
                        'score_comfort': 70,
                        'score_risk': 40,
                        'score_time': 50,
                        'score_pleasure': 75,
                    },
                    {
                        'title': 'Pociąg',
                        'description': 'Podróż koleją, widoki za oknem',
                        'node_type': 'decision',
                        'section': 'transport',
                        'order': 0,
                        'estimated_cost_percent': 20,
                        'score_comfort': 75,
                        'score_risk': 20,
                        'score_time': 60,
                        'score_pleasure': 70,
                    },
                ]
            },
            {
                'title': 'Nocleg',
                'description': 'Miejsce zakwaterowania',
                'node_type': 'milestone',
                'section': 'accommodation',
                'order': 1,
                'estimated_cost_percent': 0,
                'children': [
                    {
                        'title': 'Hotel 5* (All Inclusive)',
                        'description': 'Luksusowy hotel z pełnym wyżywieniem',
                        'node_type': 'decision',
                        'section': 'accommodation',
                        'order': 1,
                        'estimated_cost_percent': 40,
                        'score_comfort': 95,
                        'score_risk': 10,
                        'score_time': 85,
                        'score_pleasure': 90,
                    },
                    {
                        'title': 'Apartament (Airbnb)',
                        'description': 'Prywatny apartament, własna kuchnia',
                        'node_type': 'decision',
                        'section': 'accommodation',
                        'order': 1,
                        'estimated_cost_percent': 25,
                        'score_comfort': 80,
                        'score_risk': 30,
                        'score_time': 70,
                        'score_pleasure': 80,
                    },
                    {
                        'title': 'Hostel',
                        'description': 'Ekonomiczne zakwaterowanie, atmosfera',
                        'node_type': 'decision',
                        'section': 'accommodation',
                        'order': 1,
                        'estimated_cost_percent': 10,
                        'score_comfort': 55,
                        'score_risk': 35,
                        'score_time': 65,
                        'score_pleasure': 65,
                    },
                ]
            },
            {
                'title': 'Atrakcje',
                'description': 'Aktywności i zwiedzanie',
                'node_type': 'milestone',
                'section': 'activities',
                'order': 2,
                'estimated_cost_percent': 0,
                'children': [
                    {
                        'title': 'Wycieczki Zorganizowane',
                        'description': 'Pakiet wycieczek z przewodnikiem',
                        'node_type': 'decision',
                        'section': 'activities',
                        'order': 2,
                        'estimated_cost_percent': 20,
                        'score_comfort': 85,
                        'score_risk': 15,
                        'score_time': 75,
                        'score_pleasure': 85,
                    },
                    {
                        'title': 'Zwiedzanie na Własną Rękę',
                        'description': 'Samodzielne odkrywanie okolicy',
                        'node_type': 'decision',
                        'section': 'activities',
                        'order': 2,
                        'estimated_cost_percent': 10,
                        'score_comfort': 70,
                        'score_risk': 40,
                        'score_time': 60,
                        'score_pleasure': 80,
                    },
                ]
            },
        ]
    },
    'renovation': {
        'title': 'Remont Mieszkania',
        'description': 'Kompleksowy plan remontu mieszkania',
        'icon': 'hammer',
        'nodes': [
            {
                'title': 'Wybór Ekipy Remontowej',
                'description': 'Kto wykona prace remontowe',
                'node_type': 'milestone',
                'section': 'services',
                'order': 0,
                'estimated_cost_percent': 0,
                'children': [
                    {
                        'title': 'Profesjonalna Firma Budowlana',
                        'description': 'Doświadczona firma z gwarancją',
                        'node_type': 'decision',
                        'section': 'services',
                        'order': 0,
                        'estimated_cost_percent': 40,
                        'score_comfort': 90,
                        'score_risk': 15,
                        'score_time': 80,
                        'score_pleasure': 85,
                    },
                    {
                        'title': 'Samodzielni Fachowcy',
                        'description': 'Sprawdzeni rzemieślnicy, niższa cena',
                        'node_type': 'decision',
                        'section': 'services',
                        'order': 0,
                        'estimated_cost_percent': 25,
                        'score_comfort': 70,
                        'score_risk': 40,
                        'score_time': 60,
                        'score_pleasure': 70,
                    },
                    {
                        'title': 'Remont Systemem Gospodarczym',
                        'description': 'Własna praca + pomoc znajomych',
                        'node_type': 'decision',
                        'section': 'services',
                        'order': 0,
                        'estimated_cost_percent': 10,
                        'score_comfort': 50,
                        'score_risk': 70,
                        'score_time': 40,
                        'score_pleasure': 60,
                    },
                ]
            },
            {
                'title': 'Materiały Wykończeniowe',
                'description': 'Płytki, panele, farby',
                'node_type': 'milestone',
                'section': 'equipment',
                'order': 1,
                'estimated_cost_percent': 0,
                'children': [
                    {
                        'title': 'Materiały Premium',
                        'description': 'Najwyższa jakość, renomowane marki',
                        'node_type': 'decision',
                        'section': 'equipment',
                        'order': 1,
                        'estimated_cost_percent': 30,
                        'score_comfort': 90,
                        'score_risk': 10,
                        'score_time': 75,
                        'score_pleasure': 90,
                    },
                    {
                        'title': 'Materiały Średniej Klasy',
                        'description': 'Dobry stosunek jakości do ceny',
                        'node_type': 'decision',
                        'section': 'equipment',
                        'order': 1,
                        'estimated_cost_percent': 20,
                        'score_comfort': 75,
                        'score_risk': 25,
                        'score_time': 70,
                        'score_pleasure': 75,
                    },
                ]
            },
            {
                'title': 'Meble i Wyposażenie',
                'description': 'Meble kuchenne, łazienkowe, szafy',
                'node_type': 'milestone',
                'section': 'equipment',
                'order': 2,
                'estimated_cost_percent': 0,
                'children': [
                    {
                        'title': 'Meble na Wymiar',
                        'description': 'Projektowane indywidualnie',
                        'node_type': 'decision',
                        'section': 'equipment',
                        'order': 2,
                        'estimated_cost_percent': 25,
                        'score_comfort': 95,
                        'score_risk': 20,
                        'score_time': 60,
                        'score_pleasure': 90,
                    },
                    {
                        'title': 'Meble Modułowe (IKEA)',
                        'description': 'Gotowe rozwiązania, szybki montaż',
                        'node_type': 'decision',
                        'section': 'equipment',
                        'order': 2,
                        'estimated_cost_percent': 15,
                        'score_comfort': 75,
                        'score_risk': 15,
                        'score_time': 85,
                        'score_pleasure': 70,
                    },
                ]
            },
        ]
    },
}


def get_all_templates():
    """Zwraca listę wszystkich dostępnych szablonów (bez szczegółów węzłów)"""
    return [
        {
            'id': template_id,
            'title': template_data['title'],
            'description': template_data['description'],
            'icon': template_data['icon'],
        }
        for template_id, template_data in TEMPLATES.items()
    ]


def get_template(template_id):
    """Zwraca pełny szablon po ID"""
    return TEMPLATES.get(template_id)
