# Generated by Django 5.0.1 on 2026-02-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_multi_scoring_and_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decisionnode',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='decisionnode',
            name='order',
            field=models.IntegerField(default=0, help_text='Chronological order (0 = first, higher = later)'),
        ),
        migrations.AddField(
            model_name='decisionnode',
            name='section',
            field=models.CharField(choices=[('general', 'General'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('food', 'Food & Drinks'), ('entertainment', 'Entertainment'), ('activities', 'Activities'), ('services', 'Services'), ('equipment', 'Equipment'), ('other', 'Other')], default='general', help_text='Category/section of this decision', max_length=50),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Message sender role', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
