# Generated by Django 5.0.1 on 2026-02-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_decisionnode_options_decisionnode_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionnode',
            name='node_type',
            field=models.CharField(choices=[('decision', 'Decision'), ('milestone', 'Milestone')], default='decision', help_text='Type of node: decision (with ratings) or milestone (organizational)', max_length=20),
        ),
    ]
