# Generated by Django 5.0.1 on 2026-02-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for this task', null=True),
        ),
    ]
