# Generated by Django 5.0.1 on 2026-02-22 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionnode',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost incurred (filled manually during execution)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
